version: '3.9'

services:
  addok-server:
    image: communecter/addok-server
    privileged: true
    environment:
      ADDOK_FILTERS: citycode,postcode,type
      ADDOK_CLUSTER_NUM_NODES: 1
    ports:
      - '5000:5000'
    volumes:
      - ./data/addok.conf:/data/addok.conf
      - ./data/addok.db:/data/addok.db
      - ./data/dump.rdb:/data/dump.rdb
